### ISSUE TITLE
improve test coverage and remove outdate code

### ISSUE THREAD

**Issue by alincode** [ethereum/play#78]
## `@todo`
* [ ] bring test coverage across all versions to 100% and re-use all tests written by the solidity team
* [ ] run all tests in the browser inside an iframe and report to the parent window

---
<img width="875" alt="2018-12-08 01 20 49" src="https://user-images.githubusercontent.com/7610755/49662705-898c4380-fa87-11e8-8659-e8d538f96ad2.png">

![2018-12-08 01 21 19](https://user-images.githubusercontent.com/7610755/49662733-9872f600-fa87-11e8-9654-811c27176e70.png)

**Comment by alincode** [comment]
![2019-01-23 00 42 35](https://user-images.githubusercontent.com/7610755/51550675-d1d0bb00-1ea7-11e9-93cd-679a24cbd419.png)

**Comment by serapath** [comment]
We somehow need to monitor https://github.com/ethereum/solc-js/commits/master to see when they change or update the compiler and update our compiler accordingly.

Maybe a release of our `solc-js` module should hard-code the newest available compiler version, so that the compiler on purpose ignores all compiler versions found in the version list that are newer than the version available when we made a release, so that our app doesnt break because solidity released a new incompatible version which breaks our app because they maybe changed their output format again.
**what do you think?**

In any case - we should find a way how we can re-run all the tests they constantly update on our compiler version. (see: https://github.com/ethereum/solc-js/tree/master/test)
